### ISSUE TITLE
Add user feedback/testimonials to website

### ISSUE THREAD

**Issue by unquietpirate** [betterangels/buoy#123]
Just got some great user feedback/testimonials from the Tech4Justice folks -- these are from users who helped test Buoy and submitted issues. I'm pasting some excerpts here. Was thinking we could add them to the website, maybe in the Buoy in the Media section. Since there's not much there yet, we could make it a Media and User Testimonials section for now? http://buoy.maymay.net/press/#main

Here are the excerpts:

"Buoy appealed to me because of its unique approach to safety. It allows you to set up a group of people you might want to contact in case of an emergency and will send your location to that group. I really liked the fact that you could use it before anything happened as opposed to calling 911 where they won't do anything until after an event has happened. I was among the lucky few who were the first to use Buoy and I was amazed at how well it worked should a dangerous situation arise. I will definitely continue to use Buoy to keep me and my loved ones safe." - Sterling Sykora

"I was impressed by Buoy’s multi-platform functionality/UI, even in the early stages of development. Additionally, I was impressed by the commitment to keeping Buoy entirely non-proprietary and open-source. I believe the concept of Buoy fills an unmet need for a trustworthy, private, web-based emergency alert and communication system, and I am glad to have played a role in its development." - Scott Burck

"The primary purpose of Buoy as an aid application for domestic violence is a really fascinating idea which will bring help to those in need when people do not want to call the police. The victims can use Buoy to communicate with their close people when they feel that calling the police will not improve the situation. [Testing Buoy] was a new experience for me, I never really work in a small project with such big impact. I was able to see how it all begins even if working on just testing and translating. It also opens my mind that I can work in technology in my house and still be able to help people all around the world. I was impress by the amount of time and dedication that all the people who works (testing, programming, and many more) on Buoy." - Jose Villalba

**Comment by fabacab** [comment]
Would be really nice to have faces or some other contextual information to go along with these names. :)

**Comment by fabacab** [comment]
Done in b846cb23d5e90caf80ba2071122fa2e798bb66f7.
