### ISSUE TITLE
Rest API Conflict

### ISSUE THREAD

**Issue by misfist** [betterangels/buoy#137]
Upon activation, the plugin produces an error.
- Platform: Mac
- Browser: Mozilla Firefox
- URL: https://icarus.dev.glocal.coop/
- Is it reproducible: Yes
# Steps to Produce/Reproduce
1. Install Buoy
2. Activate
# Expected Results

The plugin should successfully activate without errors.
# Actual Results

Upon activation, the plugin produces the following error. 

`PHP Fatal error:  Cannot redeclare _add_extra_api_post_type_arguments() (previously declared in /srv/www/icarus/htdocs/wp-content/plugins/custom-contact-forms/wp-api/plugin.php:101) in /srv/www/icarus/htdocs/wp-content/plugins/rest-api/plugin.php on line 121`
# Workarounds

Deactivating the Custom Contact Form plugin resolves the issue. However, the plugin is needed. 

I recommend (both plugins) check for the Rest API ( perhaps check for function `create_initial_rest_routes` ) before installing or activating it.
# Other Information

The Custom Contact Form plugin includes a copy of the Rest API and Buoy auto-installs and activates another copy of the Rest API upon activation.

Ref: https://github.com/tlovett1/custom-contact-forms

**Comment by fabacab** [comment]
Good catch, thanks.

For what it's worth, Buoy does check for the existence of the REST API plugin. It sounds like what's happening is that the REST API functions bundled with Custom Contact Form aren't packaged as a plugin _registered with WordPress_ but rather simply included and defined in the global namespace.

If this suspicion is correct, this is really a bug with the Custom Contact Form plugin, not with Buoy.

I'll investigate this and send a patch to CCF if I'm correct.

**Comment by fabacab** [comment]
Oh, have a look at tlovett1/custom-contact-forms#230. Looks like this issue is already known and fixed in the latest CCF plugin's `develop` commits. Can you try testing with the latest development copy of the Custom Contact Form plugin and let me know if this is still an issue?

**Comment by hurtstotouchfire** [comment]
It sounds like this is *maybe* no longer a problem? Can we close this pending reoccurrence?
