### ISSUE TITLE
Map does not pinpoint precise location

### ISSUE THREAD

**Issue by christyleos** [betterangels/buoy#170]
* Buoy version: 0.3.2
* Platform: iPhone 5, Version 10.1 (14B72); carrier: AT&T
* Browser: Safari
* URL:  https://buoyde.vps-1952.devpanel.net/wp-admin/?page=buoy_chat&buoy_hash=0cb9f9ed41acefba6a45a4701dbe002a567f5bd57c9ffe59e50d1899b6757c27&buoy_nonce=262d311aa2RRep
* Is it reproducible: This is the first time that one of the users showed up at a vastly different place altogether, when she was actually at work.  

# Steps to Produce/Reproduce

1. User sent out alert.  
2. User left Buoy and waited for the other team members to respond. 
3. The following day, user went back on Buoy and clicked on the megaphone on the top panel and clicked on the conversation. 
4. User got the emergency message screen and clicked on the pinpoint symbol to open the map. 
5. User clicked on each person’s avatar to see where it said that they were. 
6. One of the responders on user's team appeared on the map as being at her home (Southwest of work), even though she and her phone are at work (where the testing occurs), and she is using Buoy.  
![wrong-address](https://cloud.githubusercontent.com/assets/15221858/20156928/0f5c681e-a698-11e6-8a68-39265f406044.jpg)
 

# Expected Results

User and responder would show up in their correct locations on the map.

# Actual Results

One responder showed up in a vastly different location on the map. 

# Workarounds

None that the users saw

# Other

Users' location is always wrong by a small amount using the current map version.

**Comment by fabacab** [comment]
This doesn't sound like a bug. The positions of the icons are the last known locations of the respective accounts. If someone goes to point A, closes Buoy, and then goes to point B, then as far as Buoy knows, that person is still at point A.
