### ISSUE TITLE
[documentation] VVV vagrant up system crash on Windows 10 pro w/ Hyper-V

### ISSUE THREAD

**Issue by smpsnr** [betterangels/buoy#191]
Starting a VVV Vagrant environment caused a blue screen on my machine; disabling Hyper-V (via "Turn Windows features on and off") fixed the problem. Not sure if this is an issue with VVV, Vagrant, or Virtual Box but it might be worth mentioning in the developer documentation.

**Comment by fabacab** [comment]
Definitely not a Buoy issue. You probably don't need to mention this in Buoy's developer docs, you should escalate to VVV and/or Vagrant itself.
