### ISSUE TITLE
A YouTube Video that shows all of the issues described in previous posts

### ISSUE THREAD

**Issue by the-phoebe** [betterangels/buoy#226]
A YouTube Video that shows all of the issues described in previous posts (I know you're probably going to close this report @meitar , but this post is dedicated to you^_^) 

There's no audio bc I had the hiccups at the time of filming. 

https://youtu.be/I4Zpbpc3Iqs

* Buoy version: 0.3.3
* Platform: Mac 
* Browser: Safari
* URL: https://youtu.be/I4Zpbpc3Iqs
* Is it reproducible: Yes

# Steps to Produce/Reproduce

1. First step. Send message via chat to tklo responders
1. Second step. Wait for their response
1. Third step. (As a responder) send message via chat to individual in distress
1. Fourth step. wait for their response
1. Fifth step. click on any of the 'record' buttons/options presented in the tlk.o chat

# Expected Results

Buttons onclick trigger an action (such as a video recorder, or a camera etc), typed messages to individuals in tlk.o chat get both sent and received

# Actual Results

Buttons do nothing, messages in tlk.o chat are not sent or received

# Workarounds

<img src="http://i346.photobucket.com/albums/p426/pearquero/IMG_4845_zps3p8uahle.jpg" border="0" alt=" photo IMG_4845_zps3p8uahle.jpg"/>

# Other Information

pearquero@gmail.com holla!

**Comment by fabacab** [comment]
@the-phoebe This is great, but you're right, it's not its own ticket. Instead, you could (or should) comment on the existing tickets and provide this link, preferably with time stamps, as additional information.
