### ISSUE TITLE
Implement live-streaming to responders

### ISSUE THREAD

**Issue by fabacab** [betterangels/buoy#58]
We currently let responders upload a video that other responders can download, but this requires a full upload-download round trip. Instead, allow live-streaming, too. Perhaps using something like [WebTorrent](https://webtorrent.io/)?

**Comment by fabacab** [comment]
I love this. And could we allow for the option to capture streamed videos via something like [Playback](https://mafintosh.github.io/playback/)?

**Comment by fabacab** [comment]
Found Playback in [WebTorrent FAQ](https://webtorrent.io/faq) under "Can WebTorrent clients connect to normal BitTorrent clients?"

**Comment by fabacab** [comment]
So just an FYI, the newly integrated Jitsi Meet service does have a livestream feature. I haven't looked at it closely, nor have I been able to find much documentation about it, but it's there. I want to see how far we go with this before we use something like WebTorrent.

**Comment by hurtstotouchfire** [comment]
@meitar it seems like this is obsolete now. Maybe Jitsi has issues, but we will be moving forward with fixing them, not adding another service, right?

**Comment by fabacab** [comment]
> it seems like this is obsolete now. Maybe Jitsi has issues, but we will be moving forward with fixing them, not adding another service, right?

Correct. Thanks for cleaning this, @hurtstotouchfire.
