### ISSUE TITLE
Consider JavaScript Promises instead of callbacks

### ISSUE THREAD

**Issue by fabacab** [betterangels/buoy#59]
Original issue reported at: https://chat.noisebridge.net/hack-the-left/pl/1tag3xfhfff8bdtor7rming1fr

See https://github.com/kriskowal/q for a possible library to use.

**Comment by fabacab** [comment]
A further advance is to skip JavaScript Promises (in some cases) and [replace the callbacks with function generators](http://modernweb.com/2014/02/10/replacing-callbacks-with-es6-generators/) ([another post](http://www.2ality.com/2015/03/no-promises.html)).

**Comment by hurtstotouchfire** [comment]
Can we just not? JS is complicated enough. Promises are a powerful tool to harm yourself with.

**Comment by fabacab** [comment]
> Can we just not? JS is complicated enough.

A-FUCKING-MEN.
