### ISSUE TITLE
Add images to The Team section of website (and Generosity fundraiser)

### ISSUE THREAD

**Issue by unquietpirate** [betterangels/buoy#97]
Add "profile pic" type images for each member on the Team page of the static website and Generosity.com.

Team members needing pictures [on Generosity.com](https://www.generosity.com/community-fundraising/buoy-empowering-community-based-crisis-response):
- [x] @unquietpirate 
- [x] @meitar
- [x] @pnppl 
- [x] @nitishnarula 
- [x] @hannahhubbard
- [x] @christyleos
- [x] Corvinity (no GitHub?)

Team members needing pictures [on our own project website](https://betterangels.github.io/buoy/team/#team-members):
- [x] @unquietpirate 
- [x] @meitar
- [x] @pnppl 
- [x] @nitishnarula 
- [x] @hannahhubbard
- [x] @christyleos
- [x] Corvinity (no GitHub?)

**Comment by unquietpirate** [comment]
Images to use: 
"You" -- blank github use image
Corvinity -- maybe https://www.instagram.com/p/7QRJpywzJm/ ?
Christy -- not sure, will ask
Everyone else -- github user pics (unless they have another preference)

**Comment by fabacab** [comment]
Note to whoever: Best to do this using a Jekyll Datafile like [this example](https://jekyllrb.com/docs/datafiles/#example-list-of-members).

**Comment by unquietpirate** [comment]
Alternate possibility, we could ALL use Powerpuffs! :P 

Ooh, or how 'bout cute rollover graphics (i.e. http://hood.ie/community/ )with a user photo on top, and a Powerpuff when you roll over it (or vice versa)?

**Comment by unquietpirate** [comment]
Corvinity requests that we use his Twitter profile pic: 

![corvinity](https://cloud.githubusercontent.com/assets/4370462/14662239/78a92dba-0671-11e6-99d5-762ffb50bebd.jpg)

**Comment by meitar** [comment]
Team members needing pictures:

* [x] @unquietpirate 
* [x] @meitar
* [ ] @pnppl 
* [x] @nitishnarula 
* [ ] @hannahhubbard
* [ ] @christyleos

**Comment by unquietpirate** [comment]
Images for Christy:

![1400359301212](https://cloud.githubusercontent.com/assets/4370462/14692103/436fd116-0712-11e6-9a8b-e8890ae32ee5.jpg)

![christy](https://cloud.githubusercontent.com/assets/4370462/14692108/489ca0e2-0712-11e6-9461-7d5a5c421219.png)

**Comment by fabacab** [comment]
Which one where?

**Comment by unquietpirate** [comment]
For now, let's just use the photo avatar in both places. 

I'm just trying to collect Powerpuffs for everyone, too, so that we have that as options. (I was thinking for the gh.io, if it's not too much trouble, photo avatars on top -- but rollover to Powerpuffs when you mouse over them? Kind of a cute easter egg. Definitely not MVP.)

**Comment by unquietpirate** [comment]
Here are the other currently existing 'Puffs:

![static](https://cloud.githubusercontent.com/assets/4370462/14692340/b28aa944-0713-11e6-83ae-bd85d99beb90.png)

![static-1](https://cloud.githubusercontent.com/assets/4370462/14692341/b59526f0-0713-11e6-9c48-26c2b6b21c7b.png)

![asapuff](https://cloud.githubusercontent.com/assets/4370462/14692347/bf1e7cee-0713-11e6-879d-244bdbb93275.jpg)

We just need ones for @hannahhubbard and @nitishnarula (and one for @pnppl that doesn't have a background.) :D

**Comment by pnppl** [comment]
How's this? it makes my amateurishness a little more obvious (the edges are all feathered and awful), I can make a new one on that site if you like.
![avatar2](https://cloud.githubusercontent.com/assets/9787286/14693677/14b96a18-072f-11e6-9cc0-aeb7890212d5.png)

**Comment by fabacab** [comment]
@unquietpirate I'm using GitHub's avatars as the first (non-powerpuff) image. Can you tell @christyleos to update her GitHub account's avatar? That will change her image on the team page. Thanks.

**Comment by christyleos** [comment]
done

Christy Leos
_Project Manager *
*InternetBar.org http://InternetBar.org Institute *
*The Houston Bar Center_

_723 Main St. Houston, TX_
361-220-8128

**Comment by fabacab** [comment]
I don't think I'm going to have time to do the cute rollover thing but we can always add it later. :)

Meanwhile, finished adding the other images to the Generosity page so closing this out for now.

**Comment by nitishnarula** [comment]
![nitish](https://cloud.githubusercontent.com/assets/10969049/14749831/f09d760a-087e-11e6-96db-f9c676993c99.png)
